### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'weight'

### ISSUE THREAD

**Issue by ye-zero** [hkzhang91/HiNAS#3]
I did not modify the source code, but the following error occurred during training
Loading genotype from output/sr/Set14/Outline-2c3n_TC-False_ASPP-True_Res-False_Prim-NO_DEF_L/search/models/model_best.geno
2021-12-14 04:24:08,598 one_stage_nas.utils.checkpoint INFO: No checkpoint found. Initializing model from scratch
2021-12-14 04:24:08,600 one_stage_nas.trainer INFO: Model Params: 0.25M
2021-12-14 04:24:08,601 one_stage_nas.trainer INFO: Start training
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    main()
  File "train.py", line 133, in main
    train(cfg, output_dir)
  File "train.py", line 71, in train
    cfg
  File "../one_stage_nas/engine/trainer.py", line 87, in do_train
    pred, loss_dict = model(images, targets)
  File "/home/data2/yt_data/anaconda3/envs/hinas/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/data2/yt_data/anaconda3/envs/hinas/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/data2/yt_data/anaconda3/envs/hinas/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "../one_stage_nas/modeling/sr_compnet.py", line 239, in forward
    loss.append(loss_item(pred, targets) * weight)
  File "/home/data2/yt_data/anaconda3/envs/hinas/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "../one_stage_nas/modeling/loss.py", line 34, in forward
    mu1 = F.conv2d(img1, self.window, padding=self.window_size // 2, groups=self.channel)
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'weight'

**Comment by hkzhang-git** [comment]
self.weight is the kernel build manually. It should be stored in the device of cuda if is_cuda = True in line 28 of file "/one_stage_nas/modeling/loss.py". I suggest you add a breakpoint at line 28 to check does the command self.window = self.window.cuda() is really implemented.

**Comment by JuliaWasala** [comment]
hey, I checked this and found that in line 121 of `one_stage_nas/modeling/sr_compnet.py`, the SSIM Loss object (where the `self.window `command is) is created with` cuda=False`, which explains the error: the loss is on CPU, but the images on GPU. Setting this to `True` solves the issue and model can be trained.
